In [1]:
import numpy as np

In [3]:
a=np.random.randint(1,100,(5,5))
print(a)

[[27 92 10 83 44]
 [53 58 74 79 83]
 [40 20 41 58 29]
 [42 12 51  4 46]
 [28 26 78 46 74]]


In [14]:
print("The middle element of this array is", a[2,2])

The middle element of this array is 41


In [9]:
m=a.mean(axis=1)

In [12]:
print(f'The mean of each row of the array is {m}.')

The mean of each row of the array is [51.2 69.4 37.6 31.  50.4].


In [26]:
sum=a.sum()
overall_mean=sum/25
b=a[a>overall_mean]
print(overall_mean)
print(b)

47.92
[92 83 53 58 74 79 83 58 51 78 74]


In [58]:
def numpy_spiral_order(matrix):
    list=[]
    left=0
    right=len(matrix)-1
    top=0
    down=len(matrix[0])-1
    r=0
    while left<=right and top<=down:
        if r==0:
            for i in range(left,right):
                list.append(matrix[top,i])
        top+=1
        if r==1:
            for i in range(top,down):
                list.append(matrix[i,right])
        right-=1
        if r==2:
            for i in range(right,left,-1):
                list.append(matrix[down,i])
        down-=1
        if r==3:
            for i in range(down,top,-1):
                list.append(matrix[i,left])
        left+=1
        r=(r+1)%4

    return list
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

numpy_spiral_order(matrix)

        
        
        
                
    

[np.int64(1)]


[]